name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: SSH and Deploy to Webserver
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          pm2 delete LyricsQuizAPI
          cd ~/LyricsQuizAPI
          git pull origin main
          npm install --production
          pm2 start
          pm2 save